Add widget yes/no.
V1taS/Random-Pro pull request #102
Opened 2023-05-08 15:45 UTC by EvilevNikita

Widget update takes 15 minutes. Implemented translation into available languages

2023-05-08 15:47 UTC, V1taS commented on Random/Widgets/Modifiers/GradientButtonModifier.swift
> +
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/V1taS/Random-Pro/blob/ff747325ab08f66387218b848c1228bcb3cf767d/Random/Widgets/Modifiers/GradientButtonModifier.swift#L45"></span>Files should have a single trailing newline.<br />
<code>trailing_newline</code> <code>GradientButtonModifier.swift:45</code></td>
    </tr>
  </tbody>
</table>

2023-05-08 15:55 UTC, V1taS commented
<img width="994" alt="Screenshot 2023-05-08 at 17 55 07" src="https://user-images.githubusercontent.com/30578049/236871214-3a065c80-8099-4178-9fc1-723f027d8045.png">

2023-05-08 15:55 UTC, V1taS commented
Билд упал)) Такого класса или структуры не существует `ResultLabelModifier`

2023-05-08 16:04 UTC, V1taS requested changes

2023-05-08 16:04 UTC, V1taS commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +class YesNoViewModel: ObservableObject {
`final class` мы же не планируем в будущем наследовать класс?

2023-05-08 16:04 UTC, V1taS commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +        let answers = ["yes", "no"]
Лучше так написать
```
let answers = [YesNoWidgetStrings.yes,
                         YesNoWidgetStrings.no]
```

2023-05-08 16:04 UTC, V1taS commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +        result = NSLocalizedString(answers[randomIndex], comment: "")
NSLocalizedString - не используем, надо написать другую логику

2023-05-08 16:04 UTC, V1taS commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +class YesNoViewModel: ObservableObject {
Так же этот файлик надо выровнять, сейчас здесь 4 отступа везде

2023-05-08 16:04 UTC, V1taS commented on Random/Widgets/YesNoWidget/Sources/YesNoWidget.swift
> +import Foundation
Foundation входит в SwiftUI, отдельно писать не надо

2023-05-09 10:30 UTC, EvilevNikita commented on Random/Widgets/Modifiers/GradientButtonModifier.swift
> +
Removed extra line

2023-05-09 10:31 UTC, EvilevNikita commented on Random/Widgets/Modifiers/GradientButtonModifier.swift
> +struct GradientButtonModifier: ViewModifier {
Moved folder to sources.

2023-05-09 10:35 UTC, EvilevNikita commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +class YesNoViewModel: ObservableObject {
Changed class into final class. File aligned, now it have 2 space- alignment

2023-05-09 10:35 UTC, EvilevNikita commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +        let answers = ["yes", "no"]
Done

2023-05-09 10:36 UTC, EvilevNikita commented on Random/Widgets/YesNoWidget/Sources/YesNoViewModel.swift
> +        result = NSLocalizedString(answers[randomIndex], comment: "")
Change to result = answers[randomIndex]

2023-05-09 10:37 UTC, V1taS requested changes

2023-05-09 10:37 UTC, V1taS commented on Random/Widgets/YesNoWidget/Sources/YesNoWidget.swift
> +        Text(NSLocalizedString("last_update", comment: ""))
Не используем `NSLocalizedString` используем `YesNoWidgetStrings`

2023-05-09 10:37 UTC, EvilevNikita commented on Random/Widgets/YesNoWidget/Sources/YesNoWidget.swift
> +import Foundation
Deleted import Foundation

2023-05-09 10:41 UTC, EvilevNikita commented on Random/Widgets/YesNoWidget/Sources/YesNoWidget.swift
> +        Text(NSLocalizedString("last_update", comment: ""))
Fixed

2023-05-11 08:25 UTC, V1taS approved these changes

2023-05-11 08:25 UTC, merged