Feature/pavlov artem/refine the ability to choose not only a light and dark theme, but also a system one, so that there is automatic switching
V1taS/Random-Pro pull request #110
Opened 2023-05-18 18:51 UTC by ArtemPavlov72

Added new cell squircleImageAndLabelWithSegmentedControl to Settings screen instead of squircleImageAndLabelWithSwitch.

2023-05-18 19:20 UTC, V1taS requested changes

2023-05-18 19:20 UTC, V1taS commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/Factory/MainSettingsScreenFactory.swift
> +      let startSegmentIndex = {
Не оч хорошо создавать функции в функциях)


Лучше вычисляемое свойство

```
var startSegmentIndex: Int {
  guard let isDarkMode else {
    return 0
  }
  return isDarkMode ? 1 : 2
}
```

2023-05-18 19:20 UTC, V1taS commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/View/MainSettingsScreenView.swift
> +            guard let self = self else {
guard let self else {
    return
}

2023-05-18 19:20 UTC, V1taS commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/View/MainSettingsScreenView.swift
> +              self.output?.darkThemeChanged(true)
тут не совсем понятно что функция делает, лучше переименовать типа:
func applyDarkTheme(isEnabled: Bool?)

2023-05-18 19:20 UTC, V1taS commented on Random/App/Sources/Navigation/SettingsScreenCoordinator/MainSettingsScreenCoordinator.swift
> +  func darkThemeChanged(_ isEnabled: Bool?) {
applyDarkTheme(isEnabled: Bool?)

2023-05-19 10:31 UTC, ArtemPavlov72 commented on Random/App/Resources/de.lproj/Localizable.strings
> +"white" = "Helle";
Изменил на light)

2023-05-19 10:34 UTC, ArtemPavlov72 commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/Factory/MainSettingsScreenFactory.swift
> +      let startSegmentIndex = {
Заменил на вычисляемое свойство

2023-05-19 10:45 UTC, ArtemPavlov72 commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/View/MainSettingsScreenView.swift
> +              self.output?.darkThemeChanged(true)
Функцию переименовал

2023-05-19 10:45 UTC, ArtemPavlov72 commented on Random/App/Sources/Navigation/SettingsScreenCoordinator/MainSettingsScreenCoordinator.swift
> +  func darkThemeChanged(_ isEnabled: Bool?) {
Тут тоже переименовал)

2023-05-19 16:30 UTC, V1taS requested changes

2023-05-19 16:30 UTC, V1taS commented on Random/App/Resources/ru.lproj/Localizable.strings
> +"black" = "Темная";
лучше dark

2023-05-19 16:30 UTC, V1taS commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/Models/MainSettingsScreenType.swift
> +
Лишний отступ

2023-05-19 16:30 UTC, V1taS commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/View/MainSettingsScreenView.swift
> +    let whiteTheme = RandomStrings.Localizable.light  }
```
let whiteTheme = RandomStrings.Localizable.light
}
```

2023-05-19 18:23 UTC, ArtemPavlov72 commented on Random/App/Resources/ru.lproj/Localizable.strings
> +"black" = "Темная";
заменил на dark

2023-05-19 18:24 UTC, ArtemPavlov72 commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/Models/MainSettingsScreenType.swift
> +
отступ убрал

2023-05-19 18:24 UTC, ArtemPavlov72 commented on Random/App/Sources/Modules/SettingsScreen/MainSettingsScreenModule/View/MainSettingsScreenView.swift
> +    let whiteTheme = RandomStrings.Localizable.light  }
скобочку поправил

2023-05-19 19:08 UTC, V1taS approved these changes

2023-05-19 19:08 UTC, merged