Feature/sergey yukhanov/add ability to change cubes style
V1taS/Random-Pro pull request #205
Opened 2023-10-20 12:52 UTC by yukhanov

2023-10-20 13:31 UTC, V1taS commented on Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift
> +
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/V1taS/Random-Pro/blob/decd47d7a48b3f47ddd611a871a665767d3a7331/Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift#L193"></span>Limit vertical whitespace to a single empty line. Currently 2.<br />
<code>vertical_whitespace</code> <code>SettingsScreenCoordinator.swift:193</code></td>
    </tr>
  </tbody>
</table>

2023-10-21 15:52 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift
> +
fixed

2023-10-21 15:52 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift
> +
fixed

2023-10-21 18:46 UTC, ArtemPavlov72 commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesScreenModule/Presenter/CubesScreenModule.swift
> +
Лишний пробел)

2023-10-21 18:46 UTC, ArtemPavlov72 commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  // MARK: - Internal func
я бы добавил пустую строчку после этой

2023-10-22 04:03 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  // MARK: - Internal func
добавил)

2023-10-22 04:03 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesScreenModule/Presenter/CubesScreenModule.swift
> +
убрал)

2023-10-24 19:20 UTC, ArtemPavlov72 submitted a review, later dismissed

2023-10-27 15:53 UTC, V1taS requested changes

2023-10-27 15:53 UTC, V1taS commented on Random/App/Resources/Assets.xcassets/Cubes/blue/Contents.json
> +}
**Все картинки** должны быть Scales Single Scale

<img width="257" alt="Screenshot 2023-10-27 at 17 09 50" src="https://github.com/V1taS/Random-Pro/assets/30578049/31dbe5cf-c41a-4346-8cc3-9234c72d96c1">

2023-10-27 15:53 UTC, V1taS commented on Random/App/Resources/Assets.xcassets/Cubes/blue/Contents.json
> +}
Каждая картинка должна весить не более 20 КБ, твои картинки весят 200КБ, приложение оч сильно вырастет по памяти из-за этого.

Размер можно сделать 750 на 750

2023-10-27 15:53 UTC, V1taS commented on Random/App/Resources/de.lproj/Localizable.strings
> +"change_card_style" = "Sie können den Kartenstil ändern";
За дублировал строку

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesScreenModule/View/CubesView.swift
> +      }
отступы не верные

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesScreenModule/View/CubesView.swift
> +      }
```
    guard let oneSideImage = UIImage(named: model.cubesStyle.cubesSidesName.one),
          let twoSideImage = UIImage(named: model.cubesStyle.cubesSidesName.two),
          let threeSideImage = UIImage(named: model.cubesStyle.cubesSidesName.three),
          let fourSideImage = UIImage(named: model.cubesStyle.cubesSidesName.four),
          let fiveSideImage = UIImage(named: model.cubesStyle.cubesSidesName.five),
          let sixSideImage = UIImage(named: model.cubesStyle.cubesSidesName.six) else {
      return
    }
```

Вот так не проще написать?

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +/// События которые отправляем из `BottleStyleSelectionScreenModule` в `Coordinator`
коммент не верный

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +/// События которые отправляем из `Coordinator` в `BottleStyleSelectionScreenModule`
коммент про бутылочку

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +  /// События которые отправляем из `BottleStyleSelectionScreenModule` в `Coordinator`
и тут

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +/// Готовый модуль `BottleStyleSelectionScreenModule`
и тут

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  /// Выбрана карточка игрока
Карточка игрока?)

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  ///  - selectStyle: Выбрана карточка
выбран стиль кубика

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  ///  - models: Текущие бутылочки
а тут бутылочки

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Interactor/CubesStyleSelectionScreenInteractor.swift
> +  /// Сохранить стиль бутылочки
бутылочка

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Interactor/CubesStyleSelectionScreenInteractor.swift
> +
// MARK: - Private properties

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Interactor/CubesStyleSelectionScreenInteractor.swift
> +
👀

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Interactor/CubesStyleSelectionScreenInteractor.swift
> +                                             isPremium: $0.isPremium,
👀

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Presenter/CubesStyleSelectionScreenViewController.swift
> +
можно не делать пробел

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/View/CubesStyleSelectionScreenView.swift
> +  /// Выбрана карточка
👀

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/View/CubesStyleSelectionScreenView.swift
> +  ///  - style: Выбран стиль бутылочки
👀

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/View/CubesStyleSelectionScreenView.swift
> +  /// - Parameter models: Список моделек стилей бутылочки
👀

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/View/CubesStyleSelectionScreenView.swift
> +    collectionViewLayout.minimumInteritemSpacing = 8
appearance.minInset

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +  func updateStateForSections()
Это лишнее, на главном экране мы ничего не обновляем

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +extension CubesStyleSelectionScreenCoordinator: PremiumScreenCoordinatorOutput {
Это лишнее

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +    premiumScreenCoordinator.output = self
можно не подписываться

2023-10-27 15:53 UTC, V1taS commented on Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift
> +  func updateStateForSection() {
лишнее

2023-10-29 05:08 UTC, yukhanov commented on Random/App/Resources/de.lproj/Localizable.strings
> +"change_card_style" = "Sie können den Kartenstil ändern";
fixed

2023-10-29 05:11 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesScreenModule/View/CubesView.swift
> +      }
согласен, проще, исправил

2023-10-29 05:13 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +/// События которые отправляем из `BottleStyleSelectionScreenModule` в `Coordinator`
fixed

2023-10-29 05:13 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +/// События которые отправляем из `Coordinator` в `BottleStyleSelectionScreenModule`
fixed

2023-10-29 05:25 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/View/CubesStyleSelectionScreenView.swift
> +    collectionViewLayout.minimumInteritemSpacing = 8
fixed

2023-10-29 05:26 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +  func updateStateForSections()
fixed

2023-10-29 05:52 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +extension CubesStyleSelectionScreenCoordinator: PremiumScreenCoordinatorOutput {
fixed

2023-10-29 05:58 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift
> +  func updateStateForSection() {
убрал

2023-10-29 06:00 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +  /// События которые отправляем из `BottleStyleSelectionScreenModule` в `Coordinator`
поправил

2023-10-29 06:00 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Abstractions/CubesStyleSelectionScreenAbstractions.swift
> +/// Готовый модуль `BottleStyleSelectionScreenModule`
поправил

2023-10-29 06:02 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  /// Выбрана карточка игрока
стиль кубиков)

2023-10-29 06:03 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Factory/CubesStyleSelectionScreenFactory.swift
> +  ///  - models: Текущие бутылочки
поправил)

2023-10-29 06:03 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Interactor/CubesStyleSelectionScreenInteractor.swift
> +  /// Сохранить стиль бутылочки
исправил)

2023-10-29 06:04 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Interactor/CubesStyleSelectionScreenInteractor.swift
> +
done

2023-10-30 02:23 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +    premiumScreenCoordinator.output = self
fixed

2023-10-30 02:24 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Presenter/CubesStyleSelectionScreenViewController.swift
> +  private let impactFeedback = UIImpactFeedbackGenerator(style: .light)
deleted

2023-10-30 02:25 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Presenter/CubesStyleSelectionScreenViewController.swift
> +
fixed

2023-10-30 02:27 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Presenter/CubesStyleSelectionScreenViewController.swift
> +// MARK: - BottleStyleSelectionScreenViewOutput
fixed

2023-10-30 02:33 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesStyleSelectionScreenModule/Models/CubesStyleSelectionScreenModel.swift
> +  var cubesState: CubesState {
done

2023-10-30 12:32 UTC, yukhanov commented on Random/App/Resources/Assets.xcassets/Cubes/blue/Contents.json
> +}
снижен общий вес картинок с 20Мб до 6Мб

2023-10-30 17:00 UTC, V1taS requested changes

2023-10-31 02:21 UTC, yukhanov commented on Random/App/Sources/Modules/MainScreen/CubesModules/CubesScreenModule/View/CubesView.swift
> +  func updateCubesWith(model: CubesScreenModel) {
исправил в документации на модель (также поправил в CubesScreenView)

2023-10-31 02:22 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +/// Координатор `BottleStyleSelectionScreen`
fixed

2023-10-31 02:22 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +/// Псевдоним протокола Coordinator & BottleStyleSelectionScreenCoordinatorInput
fixed

2023-10-31 02:23 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/SettingsScreenCoordinator/SettingsScreenCoordinator.swift
> +                                                                                      services)
fixed)

2023-10-31 02:24 UTC, yukhanov commented on Random/App/Sources/Navigation/MainScreenCoordinator/CubesScreenCoordinators/CubesStyleSelectionScreenCoordinator/CubesStyleSelectionScreenCoordinator.swift
> +// MARK: - BottleStyleSelectionScreenCoordinator
fixed

2023-10-31 10:16 UTC, merged