Feature/create bottle sections
V1taS/Random-Pro pull request #46
Opened 2022-12-07 12:34 UTC by tatyanaaaaaa

2022-12-07 13:58 UTC, V1taS requested changes

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +  func hapticFeedback()
Тут из названия функции, просто тактильная обратная связь, не понятно при каком действии.

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let randomTime = Double.random(in: 1...5)
Вынеси эту логику в отдельную функцию

```
func generateButtonAction() {
let appearance = Appearance()
  let randomTime  = generateRandomTime(requiredNumberOfLaps)
}

// MARK: - Private

private func generateRandomTime(_ numberOfLaps: [Double]) -> Double {
    let randomTime = Double.random(in: Appearance().randomTime) // 1...5
    return (numberOfLaps ?? .zero) + randomTime
}
```

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let requiredNumberOfLaps = [1, 1.5, 2, 2.5].shuffled().first
SOLID - Принцип S

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let randomTime = Double.random(in: 1...5)
SOLID - Принцип S

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Presenter/BottleScreenModule.swift
> +    setNavigationBar()
Тут надо делать отступ

```
  override func viewDidLoad() {
     super.viewDidLoad()

     setNavigationBar()
   }
```

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Presenter/BottleScreenModule.swift
> +    super.loadView()
Тут `super.loadView()` лишнее

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Presenter/BottleScreenModule.swift
> +
лишний пробел

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  func stopAnimation()
Наверное остановить вращение бутылочки

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  func generateButtonAction()
Мы тут ничего не генерируем. 
Кнопка вращения бутылки Action

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  func hapticFeedback()
Найминг. Надо назвать так, чтобы было понятно по названию функции что она делает

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  private let generateButton = ButtonView()
кнопка не генерирует ничего) По кнопке происходит вращение бутылки

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +    setupDefaultSettings()
Тут отступ

```
  override init(frame: CGRect) {
     super.init(frame: frame)

     setupDefaultSettings()
     setupConstraints()
   }
```

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +    let sizeInset: Double = 0.4
Inset - это отступ, а это multiplier.
multiplier - это коэффициент от 0 до 1

В коде по логике написано что высота бутылки == высота экрана * 0.4 (0.4 = 40%)

можно назвать `bottleHeightMultiplier`

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Modules/MainScreen/MainScreenModule/Interactor/MainScreenInteractor.swift
> +    let titleBottle = "Бутылочка"
Оставил для тебя коммент

// TODO: - Сделать как NSLocalizedString

Удали этот коммент как пофиксишь

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/BottleScreenCoordinator/BottleScreenCoordinator.swift
> +  private var settingsScreenCoordinator: SettingsScreenCoordinatorProtocol?
Он тут не нужен

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/BottleScreenCoordinator/BottleScreenCoordinator.swift
> +  private var listResultScreenCoordinator: ListResultScreenCoordinatorProtocol?
Лишнее тут

2022-12-07 13:58 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/BottleScreenCoordinator/BottleScreenCoordinator.swift
> +    services.metricsService.track(event: .bottleScreen)
тут лишняя метрика, ты же отправляешь в координаторе главного экрана

2022-12-08 09:46 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Factory/BottleScreenFactory.swift
> +protocol BottleScreenFactoryOutput: AnyObject {
Готово

2022-12-08 09:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +  private let bottleImage = UIImageView()
Готово

2022-12-08 09:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +  // MARK: - Initialization
Готово

2022-12-08 09:51 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +  func hapticFeedback()
Готово

2022-12-08 10:24 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let requiredNumberOfLaps = [1, 1.5, 2, 2.5].shuffled().first
Готово

2022-12-08 10:27 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Presenter/BottleScreenModule.swift
> +protocol BottleScreenModuleOutput: AnyObject {
Готово

2022-12-08 10:27 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Presenter/BottleScreenModule.swift
> +    setNavigationBar()
Готово

2022-12-08 10:27 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Presenter/BottleScreenModule.swift
> +    super.loadView()
Готово

2022-12-08 10:29 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  func stopAnimation()
Готово

2022-12-08 10:33 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  func generateButtonAction()
Готово

2022-12-08 10:34 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +  func hapticFeedback()
Готово

2022-12-08 10:38 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +    setupDefaultSettings()
Готово

2022-12-08 10:39 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/View/BottleScreenView.swift
> +    let sizeInset: Double = 0.4
Готово

2022-12-08 10:44 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/BottleScreenCoordinator/BottleScreenCoordinator.swift
> +  private var settingsScreenCoordinator: SettingsScreenCoordinatorProtocol?
Готово

2022-12-08 10:44 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/BottleScreenCoordinator/BottleScreenCoordinator.swift
> +  private var listResultScreenCoordinator: ListResultScreenCoordinatorProtocol?
Готово

2022-12-08 10:45 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/BottleScreenCoordinator/BottleScreenCoordinator.swift
> +    services.metricsService.track(event: .bottleScreen)
Готово

2022-12-08 11:06 UTC, V1taS requested changes

2022-12-08 11:06 UTC, V1taS commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let totalTime = (requiredNumberOfLaps) + randomTime
Надо вынести в отдельную функцию, написал в другом комменте

2022-12-08 11:10 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
>    /// Остановка анимации бутылочки
Готово

2022-12-08 11:54 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let totalTime = (requiredNumberOfLaps) + randomTime
Готово

2022-12-08 11:54 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/BottleScreenModule/Interactor/BottleScreenInteractor.swift
> +    let randomTime =  Double.random(in: 1...5)
Не получается выносить диапазон

2022-12-08 11:59 UTC, V1taS approved these changes

2022-12-08 11:59 UTC, merged