Feature/rock paper scissors screen v2
V1taS/Random-Pro pull request #52
Opened 2022-12-14 10:57 UTC by tatyanaaaaaa

2022-12-14 11:35 UTC, V1taS requested changes

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  func didReceive(displayingGenerationResultOnLeft: RockPaperScissorsScreenModel,
Имя у параметра должно быть коротким и имя функции должно читаться как предложение и должна быть ясность что эта функция делает
`func didReceiveResultFor(leftSideModel: RockPaperScissorsScreenModel, rightSideModel: RockPaperScissorsScreenModel)`

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  ///   - displayingGenerationResultOnRight: отображение результата генерации справа
Тут нужен 1 пробел перед  `- displayingGenerationResultOnLeft: отображение результата генерации слева`

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  ///   - displayingGenerationResultOnLeft: отображение результата генерации слева
Тут нужен 1 пробел перед ` - displayingGenerationResultOnLeft: отображение результата генерации слева`

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +
Лишний пробел

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Models/RockPaperScissorsScreenModel.swift
> +  var title: String {
Тут надо добавить комментарий

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Models/RockPaperScissorsScreenModel.swift
> +  var emoji: String {
Добавить комментарий

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Presenter/RockPaperScissorsScreenModule.swift
> +    let settingsButtonIcon = UIImage(systemName: "arrow.counterclockwise")
Название кнопки не совпадает с действием

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  ///  - displayingGenerationResultOnLeft: отображение результата генерации слева
Как и в интеракторе нужен 1 пробел

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  ///  - displayingGenerationResultOnRight: отображение результата генерации справа
Как и в интеракторе нужен 1 пробел

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  func updateContentWith(displayingGenerationResultOnLeft: RockPaperScissorsScreenModel,
Такой же коммент как и в интеракторе, название параметров должно быть коротким

func updateContentWith(leftSideModel: RockPaperScissorsScreenModel, rightSideModel: RockPaperScissorsScreenModel)

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    rightResultEmojiLabel.text = "?"
Почему не константа?

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    leftResultEmojiLabel.text = "?"
Почему не константа?

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +      leftResultEmojiLabel.leadingAnchor.constraint(equalTo: leadingAnchor,
Здесь надо крепить к центру т.к. на разных экранах будет по разному выглядеть

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +      rightResultEmojiLabel.trailingAnchor.constraint(equalTo: trailingAnchor,
Здесь надо крепить к центру т.к. на разных экранах будет по разному выглядеть

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let questionLabel = "?"
Название свойства не правильное т.к. это не лайбл, это текст или заголовок, лучше назвать так
`let questionTitle = "?"`

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let maximumInset: CGFloat = 80
Будет лишней, после того как закрепишь к центру

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let lateralInsert: CGFloat = 48
Вместо жесткого отступа слева и справа лучше использовать **multiplier**, Посмотри как сделано на экране с бутылочкой
Это свойство надо удалить

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let upperInsert: CGFloat = 60
Лишнее свойство т.к. ты будешь крепить к центру

2022-12-14 11:35 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let upperResultInsert: CGFloat = 48
Inset (отступ) бывает 3-ех видов: minInset defaultInset maxInset
тут можешь назвать maxInset

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  func didReceive(displayingGenerationResultOnLeft: RockPaperScissorsScreenModel,
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  ///   - displayingGenerationResultOnRight: отображение результата генерации справа
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  ///   - displayingGenerationResultOnLeft: отображение результата генерации слева
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Models/RockPaperScissorsScreenModel.swift
> +  var title: String {
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Models/RockPaperScissorsScreenModel.swift
> +  var emoji: String {
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Presenter/RockPaperScissorsScreenModule.swift
> +    let settingsButtonIcon = UIImage(systemName: "arrow.counterclockwise")
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  ///  - displayingGenerationResultOnLeft: отображение результата генерации слева
Готово

2022-12-15 14:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  ///  - displayingGenerationResultOnRight: отображение результата генерации справа
Готово

2022-12-15 14:15 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  func updateContentWith(displayingGenerationResultOnLeft: RockPaperScissorsScreenModel,
Готово

2022-12-15 14:15 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    rightResultEmojiLabel.text = "?"
Готово

2022-12-15 14:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +      leftResultEmojiLabel.leadingAnchor.constraint(equalTo: leadingAnchor,
готово

2022-12-15 14:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +      rightResultEmojiLabel.trailingAnchor.constraint(equalTo: trailingAnchor,
готово

2022-12-15 14:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let questionLabel = "?"
Готово

2022-12-15 14:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let maximumInset: CGFloat = 80
готово

2022-12-15 14:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let upperInsert: CGFloat = 60
готово

2022-12-15 14:18 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let upperResultInsert: CGFloat = 48
готово

2022-12-15 14:29 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    leftResultEmojiLabel.text = "?"
Не понимаю зачем нужна константа

2022-12-19 10:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +      leftResultEmojiLabel.heightAnchor.constraint(equalTo: heightAnchor, multiplier: 0.2, constant: 0),
Готово

2022-12-19 10:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +      rightResultEmojiLabel.heightAnchor.constraint(equalTo: heightAnchor, multiplier: 0.2, constant: 0),
Готово

2023-01-09 12:00 UTC, V1taS commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let minInset: CGFloat = 16
`defaultInset` всегда 16

2023-01-09 12:08 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +  /// Получен результат генерации модели
Готово

2023-01-09 12:09 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +  func generate(model: RockPaperScissorsScreenModel)
Готово

2023-01-09 12:12 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +                                        leftSideScore: .zero,
Готово

2023-01-09 12:13 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +    let newLeftSideScore = model.leftSideScore + generateScore(leftSide: randomLeftSide,
Готово

2023-01-09 12:13 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +    let newRightSideScore = model.rightSideScore + generateScore(leftSide: randomLeftSide,
Готово

2023-01-09 12:13 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +    let totalResult = "0 : 0"
Готово

2023-01-09 12:14 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Factory/RockPaperScissorsScreenFactory.swift
> +    let numberOne = 1
Готово

2023-01-09 12:15 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  func didReceive(model: RockPaperScissorsScreenModel)
Готово

2023-01-09 12:15 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  func createStartModel()
Готово

2023-01-09 12:16 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Interactor/RockPaperScissorsScreenInteractor.swift
> +  func saveModel(model: RockPaperScissorsScreenModel)
Готово

2023-01-09 12:16 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Presenter/RockPaperScissorsScreenModule.swift
> +  @objc func resetCurrentGenerationAction() {
Готово

2023-01-09 12:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/Presenter/RockPaperScissorsScreenModule.swift
> +    let setTitle = NSLocalizedString("Цу-е-фа", comment: "")
Готово

2023-01-09 12:17 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  ///  - Parameters:
Готово

2023-01-09 12:18 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +  func resetCurrentGeneration()
Готово

2023-01-09 12:19 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +
Готово

2023-01-09 12:24 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +
Я оставлю пробел

2023-01-09 12:32 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let systemFont: CGFloat = 30
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                   multiplier: appearance.multiplierHeight,
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                  constant: .zero),
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                     constant: appearance.centerXInset),
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                    multiplier: appearance.multiplierHeight,
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                   constant: .zero),
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                               constant: appearance.minInset),
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                constant: -appearance.centerXInset),
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                               constant: appearance.minInset),
Готово

2023-01-09 13:40 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +                                                constant: appearance.centerXInset),
Готово

2023-01-09 13:55 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/RockPaperScissorsScreenModule/View/RockPaperScissorsScreenView.swift
> +    let minInset: CGFloat = 16
Готово

2023-01-09 14:21 UTC, V1taS approved these changes

2023-01-09 14:21 UTC, merged