Feature/sosin vitalii/add photo filter sections
V1taS/Random-Pro pull request #60
Opened 2023-01-02 17:50 UTC by V1taS

2023-01-03 11:00 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +
Лишний пробел

2023-01-03 11:02 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/View/ImageFiltersScreenView.swift
> +    // TODO: -
Удались, оставить закрытые скобки, так как функция пустая

2023-01-03 11:03 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/MainScreenModule/Models/MainScreenSection.swift
> +    /// Раздел `Филтры изображений`
Исправить "Фильтры изображений"

2023-01-03 11:04 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +
Лишний пробел

2023-01-03 11:05 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +
Лишний пробел

2023-01-07 11:08 UTC, V1taS commented on Random Pro/ApplicationServices/FeatureToggleServices/LabelsFeatureToggleModel.swift
> +  /// Раздел `Филтры изображений`
готово ✅

2023-01-07 11:08 UTC, V1taS commented on Random Pro/ApplicationServices/FeatureToggleServices/SectionsIsHiddenFTModel.swift
> +  /// Раздел `Филтры изображений`
готово ✅

2023-01-07 11:08 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Factory/ImageFiltersScreenFactory.swift
> +  // MARK: - Internal func
Уже есть :)

2023-01-07 11:09 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ  не получен к Галерее
✅ готово

2023-01-07 11:10 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +  /// Доступ  не получен к Галерее
готово ✅

2023-01-07 11:12 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +  func addImageButtonAction()
готово ✅

2023-01-07 11:13 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +
Эт норм) У меня такой стиль написания)

2023-01-07 11:13 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/View/ImageFiltersScreenView.swift
> +    // TODO: -
функция уже не пустая

2023-01-07 11:13 UTC, V1taS commented on Random Pro/Modules/MainScreen/MainScreenModule/Models/MainScreenSection.swift
> +    /// Раздел `Филтры изображений`
готово ✅

2023-01-07 11:14 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +
готово ✅

2023-01-07 11:16 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +
готово ✅

2023-01-07 13:47 UTC, tatyanaaaaaa requested changes

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ColorsScreenModule/Interactor/ColorsScreenInteractor.swift
>    /// Доступ получен к Галерее
Исправить на "Доступ к галерее получен"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ColorsScreenModule/View/ColorsScreenView.swift
>    func generateButtonAction() {
Функция генерирует рандомные цвета, название должно читаться : "generateButtonColorActoin" - генерировать цвета по нажатию на кнопку

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Factory/ImageFiltersScreenFactory.swift
> +  /// Сгенерировать новый фильтр
Название не соответствует функции ниже : "создать фильтр изображения для()"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Factory/ImageFiltersScreenFactory.swift
> +    }
Нужен пробел после фигурной скобки

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ получен к Галерее
Исправить на "Получен доступ к галерее"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ получен к Галерее для сохранения фото
Исправить на "Получен доступ к галерее для сохранения фото"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ получен к Камере
Исправить на "Получен доступ к камере"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ColorsScreenModule/Presenter/ColorsScreenViewController.swift
> +  /// Доступ к галерее не получен
Исправить на "Получен доступ к галерее"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Models/ImageFiltersScreenType.swift
> +  /// Имя фильтра
"Название фильтра"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +  /// Доступ получен к Галерее
Исправить на "Получен доступ к галерее"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +  /// Доступ получен к Камере
Исправить на "Получен доступ к камере"

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/View/ImageFiltersScreenView.swift
> +      }
Добавить пробел

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +              let imageData = image.jpegData(compressionQuality: 1) else {
Вынести 1 в Appearance

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +          let imageData = image.jpegData(compressionQuality: 1.0) else {
Вынести 1 в Appearance

2023-01-07 13:47 UTC, tatyanaaaaaa commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +      imagePickerControllerConfig.selectionLimit = 1
Вынести 1 в Appearance

2023-01-07 14:03 UTC, V1taS commented on Random Pro/Modules/MainScreen/ColorsScreenModule/Interactor/ColorsScreenInteractor.swift
>    /// Доступ получен к Галерее
готово ✅

2023-01-07 14:05 UTC, V1taS commented on Random Pro/Modules/MainScreen/ColorsScreenModule/View/ColorsScreenView.swift
>    func generateButtonAction() {
готово ✅

2023-01-07 14:08 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Factory/ImageFiltersScreenFactory.swift
> +  /// Сгенерировать новый фильтр
готово ✅

2023-01-07 14:10 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Factory/ImageFiltersScreenFactory.swift
> +    }
готово ✅

2023-01-07 14:12 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ получен к Галерее
готово ✅

2023-01-07 14:12 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ получен к Галерее для сохранения фото
+

2023-01-07 14:14 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Interactor/ImageFiltersScreenInteractor.swift
> +  /// Доступ получен к Камере
+

2023-01-07 14:15 UTC, V1taS commented on Random Pro/Modules/MainScreen/ColorsScreenModule/Presenter/ColorsScreenViewController.swift
> +  /// Доступ к галерее не получен
++

2023-01-07 14:15 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Models/ImageFiltersScreenType.swift
> +  /// Имя фильтра
++

2023-01-07 14:16 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +  /// Доступ получен к Галерее
++

2023-01-07 14:16 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/Presenter/ImageFiltersScreenViewController.swift
> +  /// Доступ получен к Камере
++

2023-01-07 14:17 UTC, V1taS commented on Random Pro/Modules/MainScreen/ImageFiltersScreenModule/View/ImageFiltersScreenView.swift
> +      }
++

2023-01-07 14:17 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +              let imageData = image.jpegData(compressionQuality: 1) else {
это лишнее

2023-01-07 14:17 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +          let imageData = image.jpegData(compressionQuality: 1.0) else {
Это лишнее

2023-01-07 14:19 UTC, V1taS commented on Random Pro/Navigation/MainScreenCoordinator/ImageFiltersScreenCoordinator/ImageFiltersScreenCoordinator.swift
> +      imagePickerControllerConfig.selectionLimit = 1
++

2023-01-07 14:21 UTC, tatyanaaaaaa approved these changes

2023-01-07 14:21 UTC, merged